jenkins:
  systemMessage: "All configuration for this controller is done as code (JCasC)"
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        password: "adminPass"
        properties:
        - timezone:
            timeZoneName: "Europe/Amsterdam"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://localhost:8080
tool:
  nodejs:
    installations:
      - name: "node"
        home: "" #required until nodejs-1.3.4 release (JENKINS-57508)
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "16.2.0"
                    npmPackagesRefreshHours: 48
jobs:
    - script: >
        pipelineJob("initialize-pipelines") {
        definition {
            cpsScm {
                scm {
                    git{
                      remote {
                        url("git@bitbucket.org:myrepo/myrepo_seed-jobs.git")
                        credentials('jenkins-bitbucket-ssh')
                      }
                      branch("*/main")
                    }
                }
            }
          }
        }
    # jobDsl queue is a bit flaky and runs into a chicken-egg problem with Jenkins startup and queueing.
    # see https://github.com/jenkinsci/configuration-as-code-plugin/issues/280
    # see also https://github.com/jenkinsci/configuration-as-code-plugin/issues/619
    # - script: queue("initialize-pipelines")

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: jenkins-bitbucket-ssh
              username: jenkins-container
              passphrase: "jenkinsPass"
              description: "Jenkins SSH Key for Bitbucket"
              privateKeySource:
                directEntry:
                  privateKey: "privateKey"